In [24]:
import pandas as pd

In [38]:
base_df = pd.read_csv('../data/상권정보_경기_202606.csv', encoding='utf-8')

In [39]:
base_df.head(10).T

,0,1,2,3,4,5,6,7,8,9
상가업소번호,MA0106202201A0208596,MA0106202201A1978539,MA0106202201A0844862,MA0106202201A0604627,MA0106202201A0624506,MA0106202201A1458077,MA0106202201A0152042,MA0106202201A0035366,MA0106202201A0361901,MA0106202201A2114089
상호명,파리바게트동탄2기시범점,비비큐서,비케이푸드/우미참치,할리스커피,아트박스용인,로라애슐리코리아덕,에렉스후와후와스시앤누들,좋은사람들메가스토어남양주해피몰점,지앤,표준반상
지점명,NaN,판교점,NaN,수원역점,중앙점,평리지점,NaN,NaN,NaN,NaN
상권업종대분류코드,I2,I2,I2,I2,G2,G2,I2,G2,G2,I2
상권업종대분류명,음식,음식,음식,음식,소매,소매,음식,소매,소매,음식
상권업종중분류코드,I210,I201,I203,I212,G213,G209,I203,G209,G218,I201
상권업종중분류명,기타 간이,한식,일식,비알코올,오락용품 소매,섬유·의복·신발 소매,일식,섬유·의복·신발 소매,장식품 소매,한식
상권업종소분류코드,I21001,I20101,I20301,I21201,G21302,G20906,I20301,G20905,G21802,I20101
상권업종소분류명,빵/도넛,백반/한정식,일식 회/초밥,카페,문구/회화용품 소매업,침구류/커튼 소매업,일식 회/초밥,기타 의류 소매업,기념품점,백반/한정식
표준산업분류코드,I56191,I56111,I56111,I56221,G47612,G47421,I56122,G47413,G47842,I56111
표준산업분류명,제과점업,한식 일반 음식점업,한식 일반 음식점업,커피 전문점,문구용품 및 회화용품 소매업,가정용 직물제품 소매업,일식 음식점업,속옷 및 잠옷 소매업,기념품; 관광 민예품 및 장식용품 소매업,한식 일반 음식점업
시도코드,41,41,41,41,41,41,41,41,41,41
시도명,경기도,경기도,경기도,경기도,경기도,경기도,경기도,경기도,경기도,경기도
시군구코드,41597,41135,41310,41115,41461,41500,41135,41360,41463,41450
시군구명,화성시 동탄구,성남시 분당구,구리시,수원시 팔달구,용인시 처인구,이천시,성남시 분당구,남양주시,용인시 기흥구,하남시
행정동코드,41597540,41135650,41310520,41115660,41461510,41500340,41135580,41360540,41463530,41450610
행정동명,동탄4동,판교동,동구동,매산동,중앙동,마장면,서현1동,양정동,상갈동,미사1동
법정동코드,4159710500,4113510800,4131010300,4111513400,4146110100,4150034031,4113510500,4136010600,4146310300,4145010900
법정동명,청계동,판교동,인창동,매산로1가,김량장동,마장면,서현동,삼패동,상갈동,망월동
지번코드,4159710500105140002,4113510800104970000,4131010300104120042,4111513400100490018,4146110100103010003,4150034031102930078,4113510500102480002,4136010600103510001,4146310300101500007,4145010900112020001
대지구분코드,1,1,1,1,1,1,1,1,1,1
대지구분명,대지,대지,대지,대지,대지,대지,대지,대지,대지,대지
지번본번지,514.0,497.0,412.0,49.0,301.0,293.0,248.0,351.0,150.0,1202.0
지번부번지,2.0,NaN,42.0,18.0,3.0,78.0,2.0,1.0,7.0,1.0
지번주소,경기도 화성시 동탄구 청계동 514-2,경기도 성남시 분당구 판교동 497,경기도 구리시 인창동 412-42,경기도 수원시 팔달구 매산로1가 49-18,경기도 용인시 처인구 김량장동 301-3,경기도 이천시 마장면 이평리 293-78,경기도 성남시 분당구 서현동 248-2,경기도 남양주시 삼패동 351-1,경기도 용인시 기흥구 상갈동 150-7,경기도 하남시 망월동 1202-1
도로명코드,415974852353,411353180044,413104388005,411153176018,414613203017,415003203146,411354340225,413603197071,414633204031,414503202055
도로명,경기도 화성시 동탄구 동탄대로시범길,경기도 성남시 분당구 서판교로,경기도 구리시 건원대로99번길,경기도 수원시 팔달구 향교로,경기도 용인시 처인구 금령로,경기도 이천시 마장면 덕평로,경기도 성남시 분당구 서현로210번길,경기도 남양주시 고산로,경기도 용인시 기흥구 백남준로,경기도 하남시 미사강변한강로
건물본번지,253,160,3,6,86,733,10,280,7,350
건물부번지,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN
건물관리번호,4159013000200010000000002,4113510800104970000000001,4131010300104120042001777,4111513400100490018049986,4146110100103010003010526,4150034031102930078002932,4113510500102480002001718,4136010600103510001000001,4146310300101500002002059,4145010900112020001000001
건물명,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
도로명주소,경기도 화성시 동탄구 동탄대로시범길 253,경기도 성남시 분당구 서판교로 160,경기도 구리시 건원대로99번길 3,경기도 수원시 팔달구 향교로 6,경기도 용인시 처인구 금령로 86,경기도 이천시 마장면 덕평로 733-20,경기도 성남시 분당구 서현로210번길 10,경기도 남양주시 고산로 280,경기도 용인시 기흥구 백남준로 7,경기도 하남시 미사강변한강로 350
구우편번호,445140.0,463410.0,471833.0,442081.0,449925.0,467812.0,463824.0,472929.0,446905.0,465150.0
신우편번호,18477,13473,11918,16455,17051,17389,13591,12245,17068,12923
동정보,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
층정보,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
호정보,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
경도,127.102754,127.094801,127.137922,127.001804,127.205822,127.365234,127.12482,127.197145,127.110118,127.201653
위도,37.202218,37.400255,37.609606,37.267526,37.235089,37.225244,37.386396,37.592925,37.269916,37.559978

In [41]:
base_df.isnull().mean() * 100 #결측비율 확인

상가업소번호         0.000000
상호명            0.000000
지점명           89.891776
상권업종대분류코드      0.000000
상권업종대분류명       0.000000
상권업종중분류코드      0.000000
상권업종중분류명       0.000000
상권업종소분류코드      0.000000
상권업종소분류명       0.000000
표준산업분류코드       0.032259
표준산업분류명        0.032259
시도코드           0.000000
시도명            0.000000
시군구코드          0.000000
시군구명           0.000000
행정동코드          0.000000
행정동명           0.000000
법정동코드          0.000000
법정동명           0.280668
지번코드           0.000000
대지구분코드         0.000000
대지구분명          0.000000
지번본번지          0.141077
지번부번지         26.251561
지번주소           0.000000
도로명코드          0.000000
도로명            0.000000
건물본번지          0.000000
건물부번지         80.005352
건물관리번호         0.558810
건물명           51.502943
도로명주소          0.000000
구우편번호          2.934828
신우편번호          0.000000
동정보          100.000000
층정보           49.629244
호정보          100.000000
경도             0.000000
위도             0.000000
dtype: float64

In [40]:
base_df.describe()

,시도코드,시군구코드,행정동코드,법정동코드,지번코드,대지구분코드,지번본번지,지번부번지,도로명코드,건물본번지,건물부번지,구우편번호,신우편번호,동정보,호정보,경도,위도
count,672680.0,672680.000000,6.726800e+05,6.726800e+05,6.726800e+05,672680.000000,671731.000000,496091.000000,6.726800e+05,672680.000000,134500.000000,652938.000000,672680.000000,0.0,0.0,672680.000000,672680.000000
mean,41.0,41354.648683,4.135517e+07,4.135479e+09,4.129653e+18,1.001815,769.324064,13.409626,4.135501e+11,202.395374,14.975450,444895.061180,14302.670344,NaN,NaN,127.010904,37.432911
std,0.0,184.645205,1.845804e+05,1.846805e+07,1.562990e+17,0.042566,967.714936,45.697748,1.846467e+09,411.123775,22.171519,22032.667158,2624.489178,NaN,NaN,0.203198,0.223298
min,41.0,41111.000000,4.111156e+07,4.111113e+09,4.111314e+14,1.000000,1.000000,1.000000,4.111120e+11,1.000000,1.000000,410050.000000,10000.000000,NaN,NaN,126.391044,36.903466
25%,41.0,41192.000000,4.119264e+07,4.119211e+09,4.119211e+18,1.000000,262.000000,2.000000,4.119244e+11,20.000000,2.000000,425842.000000,12054.000000,NaN,NaN,126.833359,37.277139
50%,41.0,41310.000000,4.131057e+07,4.131010e+09,4.131011e+18,1.000000,573.000000,5.000000,4.131044e+11,57.000000,8.000000,445360.000000,14303.000000,NaN,NaN,127.038403,37.397616
75%,41.0,41480.000000,4.148055e+07,4.148012e+09,4.148012e+18,1.000000,931.000000,10.000000,4.148034e+11,190.000000,19.000000,463839.000000,16668.000000,NaN,NaN,127.129318,37.629945
max,41.0,41830.000000,4.183041e+07,4.183041e+09,4.183041e+18,2.000000,7346.000000,1443.000000,4.183049e+11,8908.000000,601.000000,487936.000000,18635.000000,NaN,NaN,127.807489,38.230568

In [ ]:
base_df.nunique()

상가업소번호       672680
상호명          512939
지점명            1540
상권업종대분류코드        10
상권업종대분류명         10
상권업종중분류코드        75
상권업종중분류명         75
상권업종소분류코드       247
상권업종소분류명        247
표준산업분류코드        376
표준산업분류명         376
시도코드              1
시도명               1
시군구코드            47
시군구명             47
행정동코드           602
행정동명            577
법정동코드          1944
법정동명            694
지번코드         218465
대지구분코드            2
대지구분명             2
지번본번지          5001
지번부번지           809
지번주소         218465
도로명코드         21690
도로명           22192
건물본번지          3389
건물부번지           302
건물관리번호       218550
건물명           45584
도로명주소        219346
구우편번호          5339
신우편번호          6133
동정보               0
층정보             205
호정보               0
경도           228962
위도           228961
dtype: int64

In [20]:
sorted(basedt['시군구명'].unique())

['가평군',
 '고양시 덕양구',
 '고양시 일산동구',
 '고양시 일산서구',
 '과천시',
 '광명시',
 '광주시',
 '구리시',
 '군포시',
 '김포시',
 '남양주시',
 '동두천시',
 '부천시 소사구',
 '부천시 오정구',
 '부천시 원미구',
 '성남시 분당구',
 '성남시 수정구',
 '성남시 중원구',
 '수원시 권선구',
 '수원시 영통구',
 '수원시 장안구',
 '수원시 팔달구',
 '시흥시',
 '안산시 단원구',
 '안산시 상록구',
 '안성시',
 '안양시 동안구',
 '안양시 만안구',
 '양주시',
 '양평군',
 '여주시',
 '연천군',
 '오산시',
 '용인시 기흥구',
 '용인시 수지구',
 '용인시 처인구',
 '의왕시',
 '의정부시',
 '이천시',
 '파주시',
 '평택시',
 '포천시',
 '하남시',
 '화성시 동탄구',
 '화성시 만세구',
 '화성시 병점구',
 '화성시 효행구']

1. 청년층 인구 비중이 높은 지역일수록 헬스장·PC방·카페의 인구 대비 업소 밀도가 높을 것이다. # 주 분석방향
2. 청년층 인구 비중과의 관계 정도는 헬스장·PC방·카페마다 다를 것이다. # 업종별 차이
3. 단순 업소 수와 청년층 인구 1만 명당 업소 수를 비교하면 지역 순위가 달라질 것이다. # 정규화
4. 청년층 비율이 비슷한 지역들 사이에서도 특정 업종 밀도가 유난히 높거나 낮은 지역이 존재할 것이다. # 이상치

In [27]:
age_df = pd.read_csv('../db/202606_연령별인구현황_월간.csv', encoding='cp949')
age_df

,행정구역,2026년06월_계_총인구수,2026년06월_계_연령구간인구수,2026년06월_계_20세,2026년06월_계_21세,2026년06월_계_22세,2026년06월_계_23세,2026년06월_계_24세,2026년06월_계_25세,2026년06월_계_26세,...,2026년06월_여_30세,2026년06월_여_31세,2026년06월_여_32세,2026년06월_여_33세,2026년06월_여_34세,2026년06월_여_35세,2026년06월_여_36세,2026년06월_여_37세,2026년06월_여_38세,2026년06월_여_39세
0,경기도 (4100000000),"13,761,783","3,463,598","120,911","121,934","129,695","130,374","142,580","166,585","173,296",...,"91,257","91,836","94,845","97,477","98,789","92,338","89,471","89,068","87,333","88,354"
1,경기도 수원시 (4111000000),"1,185,770","348,068","11,066","11,596","13,127","13,668","15,230","17,931","18,664",...,"9,774","9,670","9,603","9,797","9,492","8,785","8,265","8,015","7,677","7,731"
2,경기도 수원시 장안구 (4111100000),"269,984","72,708","2,843","2,978","3,430","3,583","3,702","4,293","4,237",...,"1,837","1,849","1,782","1,833","1,757","1,635","1,507","1,496","1,429","1,474"
3,경기도 수원시 권선구 (4111300000),"360,286","101,673","2,982","3,036","3,408","3,460","4,027","4,739","5,155",...,"3,012","2,952","2,932","2,949","2,850","2,647","2,452","2,298","2,319","2,247"
4,경기도 수원시 팔달구 (4111500000),"193,401","60,546","1,620","1,819","2,130","2,312","2,711","3,226","3,403",...,"1,812","1,737","1,640","1,735","1,634","1,499","1,358","1,264","1,160","1,215"
5,경기도 수원시 영통구 (4111700000),"362,099","113,141","3,621","3,763","4,159","4,313","4,790","5,673","5,869",...,"3,113","3,132","3,249","3,280","3,251","3,004","2,948","2,957","2,769","2,795"
6,경기도 성남시 (4113000000),"902,344","236,493","7,449","7,929","8,504","8,598","9,080","10,843","11,805",...,"6,594","6,450","6,628","6,818","6,954","6,595","6,352","6,262","6,206","6,170"
7,경기도 성남시 수정구 (4113100000),"234,639","63,702","1,702","2,010","2,347","2,364","2,528","2,927","3,148",...,"1,722","1,653","1,779","1,857","1,820","1,772","1,652","1,596","1,578","1,497"
8,경기도 성남시 중원구 (4113300000),"200,064","53,520","1,473","1,665","1,726","1,833","2,021","2,417","2,810",...,"1,537","1,562","1,551","1,557","1,514","1,412","1,255","1,260","1,234","1,213"
9,경기도 성남시 분당구 (4113500000),"467,641","119,271","4,274","4,254","4,431","4,401","4,531","5,499","5,847",...,"3,335","3,235","3,298","3,404","3,620","3,411","3,445","3,406","3,394","3,460"
10,경기도 의정부시 (4115000000),"461,917","113,202","4,063","4,132","4,490","4,561","5,138","5,806","6,023",...,"3,112","3,038","3,110","3,099","3,240","2,868","2,851","2,705","2,751","2,690"
11,경기도 안양시 (4117000000),"562,305","149,524","4,953","4,891","5,127","5,312","5,475","6,718","6,885",...,"4,085","4,259","4,394","4,623","4,667","4,274","4,174","4,077","3,946","3,813"
12,경기도 안양시 만안구 (4117100000),"233,711","61,567","1,940","1,973","2,179","2,273","2,312","2,814","2,994",...,"1,654","1,791","1,810","1,897","1,819","1,632","1,631","1,531","1,489","1,392"
13,경기도 안양시 동안구 (4117300000),"328,594","87,957","3,013","2,918","2,948","3,039","3,163","3,904","3,891",...,"2,431","2,468","2,584","2,726","2,848","2,642","2,543","2,546","2,457","2,421"
14,경기도 부천시 (4119000000),"755,453","186,986","6,142","6,299","6,818","6,952","7,666","9,155","9,439",...,"5,266","5,320","5,301","5,268","5,369","4,989","4,749","4,648","4,626","4,584"
15,경기도 부천시 원미구 (4119200000),"382,339","99,018","3,179","3,296","3,642","3,743","4,026","4,871","5,086",...,"2,818","2,890","2,863","2,741","2,854","2,653","2,541","2,512","2,436","2,521"
16,경기도 부천시 소사구 (4119400000),"224,202","51,795","1,802","1,810","1,880","1,820","2,090","2,401","2,402",...,"1,367","1,390","1,479","1,534","1,599","1,508","1,438","1,384","1,466","1,368"
17,경기도 부천시 오정구 (4119600000),"148,912","36,173","1,161","1,193","1,296","1,389","1,550","1,883","1,951",...,"1,081","1,040",959,993,916,828,770,752,724,695
18,경기도 광명시 (4121000000),"303,666","78,529","2,890","2,819","2,984","2,803","3,175","3,433","3,669",...,"2,110","2,229","2,388","2,427","2,487","2,216","2,129","2,084","2,070","2,052"
19,경기도 평택시 (4122000000),"619,670","173,887","5,003","5,174","5,399","5,651","6,455","7,759","8,788",...,"4,368","4,389","4,718","4,754","4,810","4,465","4,262","4,169","4,082","4,151"
20,경기도 동두천시 (4125000000),"86,265","16,554",699,733,801,752,798,923,914,...,415,401,373,400,383,381,335,338,361,383
21,경기도 안산시 (4127000000),"609,240","162,566","5,675","6,125","6,692","7,002","7,740","9,012","9,374",...,"4,315","4,197","4,133","3,996","4,092","3,513","3,339","3,208","3,088","3,067"
22,경기도 안산시 상록구 (4127100000),"320,773","84,014","3,141","3,376","3,700","3,850","4,271","4,931","4,971",...,"2,197","2,115","2,127","2,033","1,951","1,715","1,540","1,534","1,507","1,486"
23,경기도 안산시 단원구 (4127300000),"288,467","78,552","2,534","2,749","2,992","3,152","3,469","4,081","4,403",...,"2,118","2,082","2,006","1,963","2,141","1,798","1,799","1,674","1,581","1,581"
24,경기도 고양시 (4128000000),"1,057,438","260,505","8,952","9,310","9,974","9,973","10,883","12,849","13,537",...,"7,159","7,350","7,406","7,695","7,688","7,415","6,962","6,871","6,632","6,660"
25,경기도 고양시 덕양구 (4128100000),"483,048","120,201","3,752","3,928","4,251","4,352","4,550","5,413","5,669",...,"3,319","3,464","3,565","3,732","3,834","3,675","3,493","3,403","3,274","3,273"
26,경기도 고양시 일산동구 (4128500000),"298,269","76,064","2,565","2,599","2,796","2,848","3,320","3,966","4,198",...,"2,154","2,208","2,155","2,279","2,183","2,106","1,907","1,979","1,860","1,861"
27,경기도 고양시 일산서구 (4128700000),"276,121","64,240","2,635","2,783","2,927","2,773","3,013","3,470","3,670",...,"1,686","1,678","1,686","1,684","1,671","1,634","1,562","1,489","1,498","1,526"
28,경기도 과천시 (4129000000),"80,832","20,609",652,671,728,651,817,840,881,...,546,576,581,653,723,696,617,703,665,723
29,경기도 구리시 (4131000000),"187,782","47,449","1,614","1,635","1,711","1,707","1,893","2,334","2,398",...,"1,377","1,309","1,382","1,459","1,405","1,222","1,264","1,114","1,115","1,077"
30,경기도 남양주시 (4136000000),"727,440","159,026","6,820","6,791","6,997","6,783","7,246","8,117","8,073",...,"4,136","4,177","4,144","4,273","4,311","4,073","4,057","4,053","4,103","4,273"
31,경기도 오산시 (4137000000),"253,590","69,780","2,325","2,343","2,368","2,429","2,635","3,007","3,235",...,"1,660","1,722","1,853","1,912","1,960","1,864","1,802","1,750","1,788","1,871"
32,경기도 시흥시 (4139000000),"514,831","130,329","4,691","4,682","4,898","4,948","5,327","6,071","6,396",...,"3,356","3,259","3,428","3,459","3,614","3,440","3,376","3,416","3,323","3,379"
33,경기도 군포시 (4141000000),"249,462","62,954","2,258","2,308","2,501","2,489","2,738","3,185","3,294",...,"1,729","1,652","1,708","1,732","1,700","1,618","1,436","1,474","1,385","1,359"
34,경기도 의왕시 (4143000000),"164,221","42,773","1,297","1,345","1,460","1,441","1,624","1,928","1,970",...,"1,124","1,164","1,287","1,356","1,400","1,303","1,284","1,208","1,119","1,166"
35,경기도 하남시 (4145000000),"327,495","81,069","2,569","2,477","2,631","2,663","2,943","3,492","3,605",...,"2,260","2,235","2,365","2,524","2,635","2,544","2,463","2,576","2,473","2,565"
36,경기도 용인시 (4146000000),"1,090,211","263,327","11,011","11,007","11,702","11,425","12,248","13,699","13,480",...,"6,571","6,586","6,749","6,996","7,115","6,717","6,620","6,766","6,615","6,912"
37,경기도 용인시 처인구 (4146100000),"286,391","69,751","2,706","2,622","2,846","2,997","3,144","3,490","3,532",...,"1,679","1,702","1,810","1,903","1,893","1,694","1,696","1,695","1,619","1,673"
38,경기도 용인시 기흥구 (4146300000),"434,590","105,276","4,568","4,737","4,983","4,634","5,124","5,845","5,714",...,"2,681","2,606","2,600","2,605","2,635","2,569","2,463","2,470","2,557","2,523"
39,경기도 용인시 수지구 (4146500000),"369,230","88,300","3,737","3,648","3,873","3,794","3,980","4,364","4,234",...,"2,211","2,278","2,339","2,488","2,587","2,454","2,461","2,601","2,439","2,716"
40,경기도 파주시 (4148000000),"533,387","128,854","4,676","4,544","4,660","4,669","5,064","5,943","6,086",...,"3,071","3,257","3,639","3,904","4,051","3,777","3,492","3,665","3,629","3,686"
41,경기도 이천시 (4150000000),"224,740","57,778","2,064","1,933","2,013","1,975","2,326","2,905","3,116",...,"1,367","1,360","1,411","1,447","1,353","1,274","1,335","1,441","1,292","1,386"
42,경기도 안성시 (4155000000),"198,785","45,725","1,857","1,896","1,975","2,109","2,159","2,461","2,358",...,"1,003","1,085","1,091","1,112","1,084","1,020",949,"1,022",996,"1,036"
43,경기도 김포시 (4157000000),"484,042","107,142","4,083","3,848","3,876","3,860","4,118","4,883","5,057",...,"2,769","2,783","2,789","3,059","3,263","3,091","3,060","3,275","3,356","3,475"
44,경기도 화성시 (4159000000),"998,746","274,125","9,074","8,522","8,903","8,566","9,264","11,107","12,073",...,"6,993","7,109","7,917","8,039","8,143","7,817","7,842","7,959","7,732","7,823"
45,경기도 화성시 만세구 (4159100000),"234,482","54,955","1,782","1,701","1,723","1,689","1,971","2,429","2,761",...,"1,297","1,216","1,301","1,247","1,383","1,310","1,330","1,378","1,375","1,404"
46,경기도 화성시 효행구 (4159300000),"160,481","42,602","1,468","1,428","1,510","1,539","1,522","1,746","1,693",...,"1,037","1,108","1,223","1,354","1,353","1,310","1,253","1,219","1,141","1,155"
47,경기도 화성시 병점구 (4159500000),"174,794","51,533","1,698","1,668","1,903","1,837","1,926","2,358","2,477",...,"1,211","1,237","1,385","1,395","1,378","1,353","1,363","1,348","1,335","1,339"
48,경기도 화성시 동탄구 (4159700000),"428,989","125,035","4,126","3,725","3,767","3,501","3,845","4,574","5,142",...,"3,448","3,548","4,008","4,043","4,029","3,844","3,896","4,014","3,881","3,925"
49,경기도 광주시 (4161000000),"399,111","89,150","3,092","3,024","3,161","3,097","3,523","4,147","4,266",...,"2,211","2,320","2,401","2,452","2,608","2,450","2,519","2,477","2,486","2,521"
50,경기도 양주시 (4163000000),"297,226","70,426","2,566","2,537","2,648","2,628","2,903","3,329","3,321",...,"1,764","1,859","1,953","2,122","2,105","2,007","1,990","1,898","1,888","1,885"
51,경기도 포천시 (4165000000),"140,468","27,704",997,997,"1,136","1,267","1,381","1,610","1,527",...,721,648,626,635,620,584,550,551,518,518
52,경기도 여주시 (4167000000),"113,506","20,810",813,801,862,825,849,"1,043","1,042",...,529,488,534,492,560,499,495,507,510,495
53,경기도 연천군 (4180000000),"42,977","8,573",292,298,345,392,511,580,536,...,170,201,192,200,187,158,135,157,165,149
54,경기도 가평군 (4182000000),"62,041","10,505",411,410,419,453,498,565,582,...,237,240,250,253,257,224,245,203,228,237
55,경기도 양평군 (4183000000),"126,822","19,176",857,857,785,725,873,910,902,...,465,503,491,521,513,459,522,476,508,517

In [35]:
age_df.head(2).T

                                    0                     1
행정구역                경기도  (4100000000)  경기도 수원시 (4111000000)
2026년06월_계_총인구수            13,761,783             1,185,770
2026년06월_계_연령구간인구수          3,463,598               348,068
2026년06월_계_20세                120,911                11,066
2026년06월_계_21세                121,934                11,596
...                               ...                   ...
2026년06월_여_35세                 92,338                 8,785
2026년06월_여_36세                 89,471                 8,265
2026년06월_여_37세                 89,068                 8,015
2026년06월_여_38세                 87,333                 7,677
2026년06월_여_39세                 88,354                 7,731

[67 rows x 2 columns]

In [31]:
age_df.columns

Index(['행정구역', '2026년06월_계_총인구수', '2026년06월_계_연령구간인구수', '2026년06월_계_20세',
       '2026년06월_계_21세', '2026년06월_계_22세', '2026년06월_계_23세', '2026년06월_계_24세',
       '2026년06월_계_25세', '2026년06월_계_26세', '2026년06월_계_27세', '2026년06월_계_28세',
       '2026년06월_계_29세', '2026년06월_계_30세', '2026년06월_계_31세', '2026년06월_계_32세',
       '2026년06월_계_33세', '2026년06월_계_34세', '2026년06월_계_35세', '2026년06월_계_36세',
       '2026년06월_계_37세', '2026년06월_계_38세', '2026년06월_계_39세', '2026년06월_남_총인구수',
       '2026년06월_남_연령구간인구수', '2026년06월_남_20세', '2026년06월_남_21세',
       '2026년06월_남_22세', '2026년06월_남_23세', '2026년06월_남_24세', '2026년06월_남_25세',
       '2026년06월_남_26세', '2026년06월_남_27세', '2026년06월_남_28세', '2026년06월_남_29세',
       '2026년06월_남_30세', '2026년06월_남_31세', '2026년06월_남_32세', '2026년06월_남_33세',
       '2026년06월_남_34세', '2026년06월_남_35세', '2026년06월_남_36세', '2026년06월_남_37세',
       '2026년06월_남_38세', '2026년06월_남_39세', '2026년06월_여_총인구수',
       '2026년06월_여_연령구간인구수', '2026년06월_여_20세', '2026년06월_여_21세',
       '2026년06월_여_22세', '2026년06월_여_23세', '2026년06월_여_24세', '2026년06월_여_25세',
       '2026년06월_여_26세', '2026년06월_여_27세', '2026년06월_여_28세', '2026년06월_여_29세',
       '2026년06월_여_30세', '2026년06월_여_31세', '2026년06월_여_32세', '2026년06월_여_33세',
       '2026년06월_여_34세', '2026년06월_여_35세', '2026년06월_여_36세', '2026년06월_여_37세',
       '2026년06월_여_38세', '2026년06월_여_39세'],
      dtype='str')

In [33]:
age_df.shape

(56, 67)

In [34]:
age_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 67 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   행정구역                56 non-null     str
 1   2026년06월_계_총인구수     56 non-null     str
 2   2026년06월_계_연령구간인구수  56 non-null     str
 3   2026년06월_계_20세      56 non-null     str
 4   2026년06월_계_21세      56 non-null     str
 5   2026년06월_계_22세      56 non-null     str
 6   2026년06월_계_23세      56 non-null     str
 7   2026년06월_계_24세      56 non-null     str
 8   2026년06월_계_25세      56 non-null     str
 9   2026년06월_계_26세      56 non-null     str
 10  2026년06월_계_27세      56 non-null     str
 11  2026년06월_계_28세      56 non-null     str
 12  2026년06월_계_29세      56 non-null     str
 13  2026년06월_계_30세      56 non-null     str
 14  2026년06월_계_31세      56 non-null     str
 15  2026년06월_계_32세      56 non-null     str
 16  2026년06월_계_33세      56 non-null     str
 17  2026년06월_계_34세      56 non-null     str
 18  2026년06월_계_35세      56 non-null     str
 19  2026년06월_계_36세      56 non-null     str
 20  2026년06월_계_37세      56 non-null     str
 21  2026년06월_계_38세      56 non-null     str
 22  2026년06월_계_39세      56 non-null     str
 23  2026년06월_남_총인구수     56 non-null     str
 24  2026년06월_남_연령구간인구수  56 non-null     str
 25  2026년06월_남_20세      56 non-null     str
 26  2026년06월_남_21세      56 non-null     str
 27  2026년06월_남_22세      56 non-null     str
 28  2026년06월_남_23세      56 non-null     str
 29  2026년06월_남_24세      56 non-null     str
 30  2026년06월_남_25세      56 non-null     str
 31  2026년06월_남_26세      56 non-null     str
 32  2026년06월_남_27세      56 non-null     str
 33  2026년06월_남_28세      56 non-null     str
 34  2026년06월_남_29세      56 non-null     str
 35  2026년06월_남_30세      56 non-null     str
 36  2026년06월_남_31세      56 non-null     str
 37  2026년06월_남_32세      56 non-null     str
 38  2026년06월_남_33세      56 non-null     str
 39  2026년06월_남_34세      56 non-null     str
 40  2026년06월_남_35세      56 non-null     str
 41  2026년06월_남_36세      56 non-null     str
 42  2026년06월_남_37세      56 non-null     str
 43  2026년06월_남_38세      56 non-null     str
 44  2026년06월_남_39세      56 non-null     str
 45  2026년06월_여_총인구수     56 non-null     str
 46  2026년06월_여_연령구간인구수  56 non-null     str
 47  2026년06월_여_20세      56 non-null     str
 48  2026년06월_여_21세      56 non-null     str
 49  2026년06월_여_22세      56 non-null     str
 50  2026년06월_여_23세      56 non-null     str
 51  2026년06월_여_24세      56 non-null     str
 52  2026년06월_여_25세      56 non-null     str
 53  2026년06월_여_26세      56 non-null     str
 54  2026년06월_여_27세      56 non-null     str
 55  2026년06월_여_28세      56 non-null     str
 56  2026년06월_여_29세      56 non-null     str
 57  2026년06월_여_30세      56 non-null     str
 58  2026년06월_여_31세      56 non-null     str
 59  2026년06월_여_32세      56 non-null     str
 60  2026년06월_여_33세      56 non-null     str
 61  2026년06월_여_34세      56 non-null     str
 62  2026년06월_여_35세      56 non-null     str
 63  2026년06월_여_36세      56 non-null     str
 64  2026년06월_여_37세      56 non-null     str
 65  2026년06월_여_38세      56 non-null     str
 66  2026년06월_여_39세      56 non-null     str
dtypes: str(67)
memory usage: 29.4 KB

In [46]:
base_df['시군구명'].unique()[:10]

<StringArray>
['화성시 동탄구', '성남시 분당구',     '구리시', '수원시 팔달구', '용인시 처인구',     '이천시',    '남양주시',
 '용인시 기흥구',     '하남시',     '파주시']
Length: 10, dtype: str

In [ ]:
age_df['행정구역'].head(10) #괄호및 코드 제거하는 전처리 필요

0           경기도  (4100000000)
1        경기도 수원시 (4111000000)
2    경기도 수원시 장안구 (4111100000)
3    경기도 수원시 권선구 (4111300000)
4    경기도 수원시 팔달구 (4111500000)
5    경기도 수원시 영통구 (4111700000)
6        경기도 성남시 (4113000000)
7    경기도 성남시 수정구 (4113100000)
8    경기도 성남시 중원구 (4113300000)
9    경기도 성남시 분당구 (4113500000)
Name: 행정구역, dtype: str

In [50]:
store_df = base_df.copy()
ageg_df = age_df.copy()

In [51]:
store_df.head(1).T

                                   0
상가업소번호          MA0106202201A0208596
상호명                     파리바게트동탄2기시범점
지점명                              NaN
상권업종대분류코드                         I2
상권업종대분류명                          음식
상권업종중분류코드                       I210
상권업종중분류명                       기타 간이
상권업종소분류코드                     I21001
상권업종소분류명                        빵/도넛
표준산업분류코드                      I56191
표준산업분류명                         제과점업
시도코드                              41
시도명                              경기도
시군구코드                          41597
시군구명                         화성시 동탄구
행정동코드                       41597540
행정동명                            동탄4동
법정동코드                     4159710500
법정동명                             청계동
지번코드             4159710500105140002
대지구분코드                             1
대지구분명                             대지
지번본번지                          514.0
지번부번지                            2.0
지번주소           경기도 화성시 동탄구 청계동 514-2
도로명코드                   415974852353
도로명              경기도 화성시 동탄구 동탄대로시범길
건물본번지                            253
건물부번지                            NaN
건물관리번호     4159013000200010000000002
건물명                              NaN
도로명주소        경기도 화성시 동탄구 동탄대로시범길 253
구우편번호                       445140.0
신우편번호                          18477
동정보                              NaN
층정보                              NaN
호정보                              NaN
경도                        127.102754
위도                         37.202218

In [52]:
ageg_df.head(1).T

                                    0
행정구역                경기도  (4100000000)
2026년06월_계_총인구수            13,761,783
2026년06월_계_연령구간인구수          3,463,598
2026년06월_계_20세                120,911
2026년06월_계_21세                121,934
...                               ...
2026년06월_여_35세                 92,338
2026년06월_여_36세                 89,471
2026년06월_여_37세                 89,068
2026년06월_여_38세                 87,333
2026년06월_여_39세                 88,354

[67 rows x 1 columns]

In [55]:
ageg_df['행정구역'].str.replace('경기도','')

0               (4100000000)
1           수원시 (4111000000)
2       수원시 장안구 (4111100000)
3       수원시 권선구 (4111300000)
4       수원시 팔달구 (4111500000)
5       수원시 영통구 (4111700000)
6           성남시 (4113000000)
7       성남시 수정구 (4113100000)
8       성남시 중원구 (4113300000)
9       성남시 분당구 (4113500000)
10         의정부시 (4115000000)
11          안양시 (4117000000)
12      안양시 만안구 (4117100000)
13      안양시 동안구 (4117300000)
14          부천시 (4119000000)
15      부천시 원미구 (4119200000)
16      부천시 소사구 (4119400000)
17      부천시 오정구 (4119600000)
18          광명시 (4121000000)
19          평택시 (4122000000)
20         동두천시 (4125000000)
21          안산시 (4127000000)
22      안산시 상록구 (4127100000)
23      안산시 단원구 (4127300000)
24          고양시 (4128000000)
25      고양시 덕양구 (4128100000)
26     고양시 일산동구 (4128500000)
27     고양시 일산서구 (4128700000)
28          과천시 (4129000000)
29          구리시 (4131000000)
30         남양주시 (4136000000)
31          오산시 (4137000000)
32          시흥시 (4139000000)
33          군포시 (4141000000)
34          의왕시 (4143000000)
35          하남시 (4145000000)
36          용인시 (4146000000)
37      용인시 처인구 (4146100000)
38      용인시 기흥구 (4146300000)
39      용인시 수지구 (4146500000)
40          파주시 (4148000000)
41          이천시 (4150000000)
42          안성시 (4155000000)
43          김포시 (4157000000)
44          화성시 (4159000000)
45      화성시 만세구 (4159100000)
46      화성시 효행구 (4159300000)
47      화성시 병점구 (4159500000)
48      화성시 동탄구 (4159700000)
49          광주시 (4161000000)
50          양주시 (4163000000)
51          포천시 (4165000000)
52          여주시 (4167000000)
53          연천군 (4180000000)
54          가평군 (4182000000)
55          양평군 (4183000000)
Name: 행정구역, dtype: str

In [56]:
ageg_df['행정구역'].str.replace(r'\([^)]*\)', '',regex=True)

0             경기도
1          경기도 수원시
2      경기도 수원시 장안구
3      경기도 수원시 권선구
4      경기도 수원시 팔달구
5      경기도 수원시 영통구
6          경기도 성남시
7      경기도 성남시 수정구
8      경기도 성남시 중원구
9      경기도 성남시 분당구
10        경기도 의정부시
11         경기도 안양시
12     경기도 안양시 만안구
13     경기도 안양시 동안구
14         경기도 부천시
15     경기도 부천시 원미구
16     경기도 부천시 소사구
17     경기도 부천시 오정구
18         경기도 광명시
19         경기도 평택시
20        경기도 동두천시
21         경기도 안산시
22     경기도 안산시 상록구
23     경기도 안산시 단원구
24         경기도 고양시
25     경기도 고양시 덕양구
26    경기도 고양시 일산동구
27    경기도 고양시 일산서구
28         경기도 과천시
29         경기도 구리시
30        경기도 남양주시
31         경기도 오산시
32         경기도 시흥시
33         경기도 군포시
34         경기도 의왕시
35         경기도 하남시
36         경기도 용인시
37     경기도 용인시 처인구
38     경기도 용인시 기흥구
39     경기도 용인시 수지구
40         경기도 파주시
41         경기도 이천시
42         경기도 안성시
43         경기도 김포시
44         경기도 화성시
45     경기도 화성시 만세구
46     경기도 화성시 효행구
47     경기도 화성시 병점구
48     경기도 화성시 동탄구
49         경기도 광주시
50         경기도 양주시
51         경기도 포천시
52         경기도 여주시
53         경기도 연천군
54         경기도 가평군
55         경기도 양평군
Name: 행정구역, dtype: str

In [ ]:
ageg_df['region_name'] = (
    ageg_df['행정구역']
    .str.replace('경기도','',regex=False)
    .str.replace(r'\([^)]*\)', '',regex=True)
    .str.strip() #공백때문에 strip 추가
)

In [81]:
ageg_df[['행정구역','region_name']]

                         행정구역 region_name
0           경기도  (4100000000)
1        경기도 수원시 (4111000000)         수원시
2    경기도 수원시 장안구 (4111100000)     수원시 장안구
3    경기도 수원시 권선구 (4111300000)     수원시 권선구
4    경기도 수원시 팔달구 (4111500000)     수원시 팔달구
5    경기도 수원시 영통구 (4111700000)     수원시 영통구
6        경기도 성남시 (4113000000)         성남시
7    경기도 성남시 수정구 (4113100000)     성남시 수정구
8    경기도 성남시 중원구 (4113300000)     성남시 중원구
9    경기도 성남시 분당구 (4113500000)     성남시 분당구
10      경기도 의정부시 (4115000000)        의정부시
11       경기도 안양시 (4117000000)         안양시
12   경기도 안양시 만안구 (4117100000)     안양시 만안구
13   경기도 안양시 동안구 (4117300000)     안양시 동안구
14       경기도 부천시 (4119000000)         부천시
15   경기도 부천시 원미구 (4119200000)     부천시 원미구
16   경기도 부천시 소사구 (4119400000)     부천시 소사구
17   경기도 부천시 오정구 (4119600000)     부천시 오정구
18       경기도 광명시 (4121000000)         광명시
19       경기도 평택시 (4122000000)         평택시
20      경기도 동두천시 (4125000000)        동두천시
21       경기도 안산시 (4127000000)         안산시
22   경기도 안산시 상록구 (4127100000)     안산시 상록구
23   경기도 안산시 단원구 (4127300000)     안산시 단원구
24       경기도 고양시 (4128000000)         고양시
25   경기도 고양시 덕양구 (4128100000)     고양시 덕양구
26  경기도 고양시 일산동구 (4128500000)    고양시 일산동구
27  경기도 고양시 일산서구 (4128700000)    고양시 일산서구
28       경기도 과천시 (4129000000)         과천시
29       경기도 구리시 (4131000000)         구리시
30      경기도 남양주시 (4136000000)        남양주시
31       경기도 오산시 (4137000000)         오산시
32       경기도 시흥시 (4139000000)         시흥시
33       경기도 군포시 (4141000000)         군포시
34       경기도 의왕시 (4143000000)         의왕시
35       경기도 하남시 (4145000000)         하남시
36       경기도 용인시 (4146000000)         용인시
37   경기도 용인시 처인구 (4146100000)     용인시 처인구
38   경기도 용인시 기흥구 (4146300000)     용인시 기흥구
39   경기도 용인시 수지구 (4146500000)     용인시 수지구
40       경기도 파주시 (4148000000)         파주시
41       경기도 이천시 (4150000000)         이천시
42       경기도 안성시 (4155000000)         안성시
43       경기도 김포시 (4157000000)         김포시
44       경기도 화성시 (4159000000)         화성시
45   경기도 화성시 만세구 (4159100000)     화성시 만세구
46   경기도 화성시 효행구 (4159300000)     화성시 효행구
47   경기도 화성시 병점구 (4159500000)     화성시 병점구
48   경기도 화성시 동탄구 (4159700000)     화성시 동탄구
49       경기도 광주시 (4161000000)         광주시
50       경기도 양주시 (4163000000)         양주시
51       경기도 포천시 (4165000000)         포천시
52       경기도 여주시 (4167000000)         여주시
53       경기도 연천군 (4180000000)         연천군
54       경기도 가평군 (4182000000)         가평군
55       경기도 양평군 (4183000000)         양평군

In [107]:
sorted(store_df['시군구명'].unique())

['가평군',
 '고양시 덕양구',
 '고양시 일산동구',
 '고양시 일산서구',
 '과천시',
 '광명시',
 '광주시',
 '구리시',
 '군포시',
 '김포시',
 '남양주시',
 '동두천시',
 '부천시 소사구',
 '부천시 오정구',
 '부천시 원미구',
 '성남시 분당구',
 '성남시 수정구',
 '성남시 중원구',
 '수원시 권선구',
 '수원시 영통구',
 '수원시 장안구',
 '수원시 팔달구',
 '시흥시',
 '안산시 단원구',
 '안산시 상록구',
 '안성시',
 '안양시 동안구',
 '안양시 만안구',
 '양주시',
 '양평군',
 '여주시',
 '연천군',
 '오산시',
 '용인시 기흥구',
 '용인시 수지구',
 '용인시 처인구',
 '의왕시',
 '의정부시',
 '이천시',
 '파주시',
 '평택시',
 '포천시',
 '하남시',
 '화성시 동탄구',
 '화성시 만세구',
 '화성시 병점구',
 '화성시 효행구']

In [ ]:
region_names = ageg_df['region_name'].unique() #소계만 추리기

del_regions = []

for region in region_names:
    sub_region = any(
        name.startswith(region + ' ')
        for name in region_names
        if name != region
    )
    
    if sub_region:
        del_regions.append(region)

In [85]:
sorted(del_regions) #strip 추가안했을땐 실행안되고 추가후에 실행됨

['고양시', '부천시', '성남시', '수원시', '안산시', '안양시', '용인시', '화성시']

In [ ]:
ageg_df = ageg_df[ #상위 시(소계) 삭제 코드
    ~ageg_df['region_name'].isin(del_regions)
].copy()

In [ ]:
ageg_df = ageg_df[ #경기도(총계) 삭제 코드
    ageg_df['region_name'].str.strip() != ''
].copy()

In [101]:
ageg_df[['행정구역','region_name']]

                         행정구역 region_name
2    경기도 수원시 장안구 (4111100000)     수원시 장안구
3    경기도 수원시 권선구 (4111300000)     수원시 권선구
4    경기도 수원시 팔달구 (4111500000)     수원시 팔달구
5    경기도 수원시 영통구 (4111700000)     수원시 영통구
7    경기도 성남시 수정구 (4113100000)     성남시 수정구
8    경기도 성남시 중원구 (4113300000)     성남시 중원구
9    경기도 성남시 분당구 (4113500000)     성남시 분당구
10      경기도 의정부시 (4115000000)        의정부시
12   경기도 안양시 만안구 (4117100000)     안양시 만안구
13   경기도 안양시 동안구 (4117300000)     안양시 동안구
15   경기도 부천시 원미구 (4119200000)     부천시 원미구
16   경기도 부천시 소사구 (4119400000)     부천시 소사구
17   경기도 부천시 오정구 (4119600000)     부천시 오정구
18       경기도 광명시 (4121000000)         광명시
19       경기도 평택시 (4122000000)         평택시
20      경기도 동두천시 (4125000000)        동두천시
22   경기도 안산시 상록구 (4127100000)     안산시 상록구
23   경기도 안산시 단원구 (4127300000)     안산시 단원구
25   경기도 고양시 덕양구 (4128100000)     고양시 덕양구
26  경기도 고양시 일산동구 (4128500000)    고양시 일산동구
27  경기도 고양시 일산서구 (4128700000)    고양시 일산서구
28       경기도 과천시 (4129000000)         과천시
29       경기도 구리시 (4131000000)         구리시
30      경기도 남양주시 (4136000000)        남양주시
31       경기도 오산시 (4137000000)         오산시
32       경기도 시흥시 (4139000000)         시흥시
33       경기도 군포시 (4141000000)         군포시
34       경기도 의왕시 (4143000000)         의왕시
35       경기도 하남시 (4145000000)         하남시
37   경기도 용인시 처인구 (4146100000)     용인시 처인구
38   경기도 용인시 기흥구 (4146300000)     용인시 기흥구
39   경기도 용인시 수지구 (4146500000)     용인시 수지구
40       경기도 파주시 (4148000000)         파주시
41       경기도 이천시 (4150000000)         이천시
42       경기도 안성시 (4155000000)         안성시
43       경기도 김포시 (4157000000)         김포시
45   경기도 화성시 만세구 (4159100000)     화성시 만세구
46   경기도 화성시 효행구 (4159300000)     화성시 효행구
47   경기도 화성시 병점구 (4159500000)     화성시 병점구
48   경기도 화성시 동탄구 (4159700000)     화성시 동탄구
49       경기도 광주시 (4161000000)         광주시
50       경기도 양주시 (4163000000)         양주시
51       경기도 포천시 (4165000000)         포천시
52       경기도 여주시 (4167000000)         여주시
53       경기도 연천군 (4180000000)         연천군
54       경기도 가평군 (4182000000)         가평군
55       경기도 양평군 (4183000000)         양평군

In [110]:
base_regions = set(store_df['시군구명'].unique()) #전처리 확인
age_regions = set(ageg_df['region_name'].unique())

print('상권dt 지역 수', len(base_regions))
print('인구db 지역 수', len(age_regions))
print('공통 지역 수', len(base_regions & age_regions))
print('상권에만 있는 지역', sorted(base_regions - age_regions))
print('인구에만 있는 지역', sorted(age_regions - base_regions))

상권dt 지역 수 47
인구db 지역 수 47
공통 지역 수 47
상권에만 있는 지역 []
인구에만 있는 지역 []

In [111]:
age_cols = [
    f'2026년06월_계_{age}세'
    for age in range(20, 40)
]

In [ ]:
ageg_df[age_cols] = (
    ageg_df[age_cols].replace(',','', regex=True).astype(int) #연령대별 인구값 문자 -> 숫자로 변환
)

In [120]:
ageg_df['age_sum'] = ageg_df[age_cols].sum(axis=1)

In [121]:
print(ageg_df['age_sum'])

2      72708
3     101673
4      60546
5     113141
7      63702
8      53520
9     119271
10    113202
12     61567
13     87957
15     99018
16     51795
17     36173
18     78529
19    173887
20     16554
22     84014
23     78552
25    120201
26     76064
27     64240
28     20609
29     47449
30    159026
31     69780
32    130329
33     62954
34     42773
35     81069
37     69751
38    105276
39     88300
40    128854
41     57778
42     45725
43    107142
45     54955
46     42602
47     51533
48    125035
49     89150
50     70426
51     27704
52     20810
53      8573
54     10505
55     19176
Name: age_sum, dtype: int64

In [ ]:
ageg_df['2026년06월_계_연령구간인구수'] = (
    ageg_df['2026년06월_계_연령구간인구수'].str.replace(',','',regex=False).astype(int) #csv 데이터값 문자 -> 숫자로 변환
)

In [ ]:
(ageg_df['age_sum'] # 20~39세 합계값과 연령구간인구수 컬럼값 비교
    == ageg_df['2026년06월_계_연령구간인구수']
).all()
#연령구간인구수 컬럼값을 청년층인구수로 사용해도 된다는 근거

np.True_

In [132]:
store_df.head(1).T

                                   0
상가업소번호          MA0106202201A0208596
상호명                     파리바게트동탄2기시범점
지점명                              NaN
상권업종대분류코드                         I2
상권업종대분류명                          음식
상권업종중분류코드                       I210
상권업종중분류명                       기타 간이
상권업종소분류코드                     I21001
상권업종소분류명                        빵/도넛
표준산업분류코드                      I56191
표준산업분류명                         제과점업
시도코드                              41
시도명                              경기도
시군구코드                          41597
시군구명                         화성시 동탄구
행정동코드                       41597540
행정동명                            동탄4동
법정동코드                     4159710500
법정동명                             청계동
지번코드             4159710500105140002
대지구분코드                             1
대지구분명                             대지
지번본번지                          514.0
지번부번지                            2.0
지번주소           경기도 화성시 동탄구 청계동 514-2
도로명코드                   415974852353
도로명              경기도 화성시 동탄구 동탄대로시범길
건물본번지                            253
건물부번지                            NaN
건물관리번호     4159013000200010000000002
건물명                              NaN
도로명주소        경기도 화성시 동탄구 동탄대로시범길 253
구우편번호                       445140.0
신우편번호                          18477
동정보                              NaN
층정보                              NaN
호정보                              NaN
경도                        127.102754
위도                         37.202218

In [137]:
store_db_cols = [
    '상가업소번호',
    '상호명',
    '상권업종대분류코드',
    '상권업종대분류명',
    '상권업종중분류코드',
    '상권업종중분류명',
    '상권업종소분류코드',
    '상권업종소분류명',
    '표준산업분류코드',
    '표준산업분류명',
    '시도코드',
    '시도명',
    '시군구명',
    '행정동코드',
    '행정동명',
    '법정동코드',
    '법정동명',
    '지번주소',
    '도로명주소',
    '신우편번호',
    '경도',
    '위도'    
]

store_rename_df = store_df[store_db_cols].copy()

In [138]:
store_rename_df = store_rename_df.rename(columns={
     '상가업소번호': 'store_id',
        '상호명': 'store_name',
        '상권업종대분류코드': 'category_large_id',
        '상권업종대분류명': 'category_large_name',
        '상권업종중분류코드': 'category_medium_id',
        '상권업종중분류명': 'category_medium_name',
        '상권업종소분류코드': 'category_small_id',
        '상권업종소분류명': 'category_small_name',
        '표준산업분류코드': 'industry_code',
        '표준산업분류명': 'industry_name',
        '시도코드': 'province_code',
        '시도명': 'province_name',
        '시군구명': 'region_name',
        '행정동코드': 'admin_dong_code',
        '행정동명': 'admin_dong_name',
        '법정동코드': 'legal_dong_code',
        '법정동명': 'legal_dong_name',
        '지번주소': 'lot_address',
        '도로명주소': 'road_address',
        '신우편번호': 'postal_code',
        '경도': 'longitude',
        '위도': 'latitude'   
})

In [143]:
year_db_cols = [
    'region_name',
    '2026년06월_계_총인구수',
    '2026년06월_계_연령구간인구수'
]

year_rename_df = ageg_df[year_db_cols].copy()

In [150]:
year_rename_df = year_rename_df.rename(columns={
        '2026년06월_계_총인구수': 'total_population',
        '2026년06월_계_연령구간인구수': 'year_population'
})

In [151]:
store_rename_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 672680 entries, 0 to 672679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   store_id              672680 non-null  str
 1   store_name            672680 non-null  str
 2   category_large_id     672680 non-null  str
 3   category_large_name   672680 non-null  str
 4   category_medium_id    672680 non-null  str
 5   category_medium_name  672680 non-null  str
 6   category_small_id     672680 non-null  str
 7   category_small_name   672680 non-null  str
 8   industry_code         672463 non-null  str
 9   industry_name         672463 non-null  str
 10  province_code         672680 non-null  int64
 11  province_name         672680 non-null  str
 12  region_name           672680 non-null  str
 13  admin_dong_code       672680 non-null  int64
 14  admin_dong_name       672680 non-null  str
 15  legal_dong_code       672680 non-null  int64
 16  legal_dong_name       670792 non-null  str
 17  lot_address           672680 non-null  str
 18  road_address          672680 non-null  str
 19  postal_code           672680 non-null  int64
 20  longitude             672680 non-null  float64
 21  latitude              672680 non-null  float64
dtypes: float64(2), int64(4), str(16)
memory usage: 112.9 MB

In [156]:
year_rename_df.info()

<class 'pandas.DataFrame'>
Index: 47 entries, 2 to 55
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   region_name       47 non-null     str
 1   total_population  47 non-null     int64
 2   year_population   47 non-null     int64
dtypes: int64(2), str(1)
memory usage: 1.5 KB

In [155]:
year_rename_df['total_population'] = (
    year_rename_df['total_population'].str.replace(',','',regex = False).astype(int))

In [154]:
print('store중복값', store_rename_df.duplicated().sum())
print('year중복값', year_rename_df.duplicated().sum())

store중복값 0
year중복값 0